def setAlpha3 (ccod,cnom)
  country = Contact::Country.where( name: cnom ).first
  if not country.nil?
    country.alpha_3 = ccod
    country.save
  else
    Contact::Country.create name: cnom, alpha_3: ccod
  end
end

setAlpha3 'ABW','Aruba'
setAlpha3 'AFG','Afghanistan'
setAlpha3 'AGO','Angola'
setAlpha3 'AIA','Anguilla'
setAlpha3 'ALA','Åland Islands'
setAlpha3 'ALB','Albania'
setAlpha3 'AND','Andorra'
setAlpha3 'ARE','United Arab Emirates'
setAlpha3 'ARG','Argentina'
setAlpha3 'ARM','Armenia'
setAlpha3 'ASM','American Samoa'
setAlpha3 'ATA','Antarctica'
setAlpha3 'ATF','French Southern Territories'
setAlpha3 'ATG','Antigua and Barbuda'
setAlpha3 'AUS','Australia'
setAlpha3 'AUT','Austria'
setAlpha3 'AZE','Azerbaijan'
setAlpha3 'BDI','Burundi'
setAlpha3 'BEL','Belgium'
setAlpha3 'BEN','Benin'
setAlpha3 'BES','Bonaire, Sint Eustatius and Saba'
setAlpha3 'BFA','Burkina Faso'
setAlpha3 'BGD','Bangladesh'
setAlpha3 'BGR','Bulgaria'
setAlpha3 'BHR','Bahrain'
setAlpha3 'BHS','Bahamas'
setAlpha3 'BIH','Bosnia and Herzegovina'
setAlpha3 'BLM','Saint Barthélemy'
setAlpha3 'BLR','Belarus'
setAlpha3 'BLZ','Belize'
setAlpha3 'BMU','Bermuda'
setAlpha3 'BOL','Bolivia, Plurinational State of'
setAlpha3 'BRA','Brazil'
setAlpha3 'BRB','Barbados'
setAlpha3 'BRN','Brunei Darussalam'
setAlpha3 'BTN','Bhutan'
setAlpha3 'BVT','Bouvet Island'
setAlpha3 'BWA','Botswana'
setAlpha3 'CAF','Central African Republic'
setAlpha3 'CAN','Canada'
setAlpha3 'CCK','Cocos (Keeling) Islands'
setAlpha3 'CHE','Switzerland'
setAlpha3 'CHL','Chile'
setAlpha3 'CHN','China'
setAlpha3 'CIV','Côte d\'Ivoire'
setAlpha3 'CMR','Cameroon'
setAlpha3 'COD','Congo, the Democratic Republic of the'
setAlpha3 'COG','Congo'
setAlpha3 'COK','Cook Islands'
setAlpha3 'COL','Colombia'
setAlpha3 'COM','Comoros'
setAlpha3 'CPV','Cabo Verde'
setAlpha3 'CRI','Costa Rica'
setAlpha3 'CUB','Cuba'
setAlpha3 'CUW','Curaçao'
setAlpha3 'CXR','Christmas Island'
setAlpha3 'CYM','Cayman Islands'
setAlpha3 'CYP','Cyprus'
setAlpha3 'CZE','Czech Republic'
setAlpha3 'DEU','Germany'
setAlpha3 'DJI','Djibouti'
setAlpha3 'DMA','Dominica'
setAlpha3 'DNK','Denmark'
setAlpha3 'DOM','Dominican Republic'
setAlpha3 'DZA','Algeria'
setAlpha3 'ECU','Ecuador'
setAlpha3 'EGY','Egypt'
setAlpha3 'ERI','Eritrea'
setAlpha3 'ESH','Western Sahara'
setAlpha3 'ESP','Spain'
setAlpha3 'EST','Estonia'
setAlpha3 'ETH','Ethiopia'
setAlpha3 'FIN','Finland'
setAlpha3 'FJI','Fiji'
setAlpha3 'FLK','Falkland Islands (Malvinas)'
setAlpha3 'FRA','France'
setAlpha3 'FRO','Faroe Islands'
setAlpha3 'FSM','Micronesia, Federated States of'
setAlpha3 'GAB','Gabon'
setAlpha3 'GBR','United Kingdom of Great Britain and Northern Ireland'
setAlpha3 'GEO','Georgia'
setAlpha3 'GGY','Guernsey'
setAlpha3 'GHA','Ghana'
setAlpha3 'GIB','Gibraltar'
setAlpha3 'GIN','Guinea'
setAlpha3 'GLP','Guadeloupe'
setAlpha3 'GMB','Gambia'
setAlpha3 'GNB','Guinea-Bissau'
setAlpha3 'GNQ','Equatorial Guinea'
setAlpha3 'GRC','Greece'
setAlpha3 'GRD','Grenada'
setAlpha3 'GRL','Greenland'
setAlpha3 'GTM','Guatemala'
setAlpha3 'GUF','French Guiana'
setAlpha3 'GUM','Guam'
setAlpha3 'GUY','Guyana'
setAlpha3 'HKG','Hong Kong'
setAlpha3 'HMD','Heard Island and McDonald Islands'
setAlpha3 'HND','Honduras'
setAlpha3 'HRV','Croatia'
setAlpha3 'HTI','Haiti'
setAlpha3 'HUN','Hungary'
setAlpha3 'IDN','Indonesia'
setAlpha3 'IMN','Isle of Man'
setAlpha3 'IND','India'
setAlpha3 'IOT','British Indian Ocean Territory'
setAlpha3 'IRL','Ireland'
setAlpha3 'IRN','Iran, Islamic Republic of'
setAlpha3 'IRQ','Iraq'
setAlpha3 'ISL','Iceland'
setAlpha3 'ISR','Israel'
setAlpha3 'ITA','Italy'
setAlpha3 'JAM','Jamaica'
setAlpha3 'JEY','Jersey'
setAlpha3 'JOR','Jordan'
setAlpha3 'JPN','Japan'
setAlpha3 'KAZ','Kazakhstan'
setAlpha3 'KEN','Kenya'
setAlpha3 'KGZ','Kyrgyzstan'
setAlpha3 'KHM','Cambodia'
setAlpha3 'KIR','Kiribati'
setAlpha3 'KNA','Saint Kitts and Nevis'
setAlpha3 'KOR','Korea, Republic of'
setAlpha3 'KWT','Kuwait'
setAlpha3 'LAO','Lao People\'s Democratic Republic'
setAlpha3 'LBN','Lebanon'
setAlpha3 'LBR','Liberia'
setAlpha3 'LBY','Libya'
setAlpha3 'LCA','Saint Lucia'
setAlpha3 'LIE','Liechtenstein'
setAlpha3 'LKA','Sri Lanka'
setAlpha3 'LSO','Lesotho'
setAlpha3 'LTU','Lithuania'
setAlpha3 'LUX','Luxembourg'
setAlpha3 'LVA','Latvia'
setAlpha3 'MAC','Macao'
setAlpha3 'MAF','Saint Martin (French part)'
setAlpha3 'MAR','Morocco'
setAlpha3 'MCO','Monaco'
setAlpha3 'MDA','Moldova, Republic of'
setAlpha3 'MDG','Madagascar'
setAlpha3 'MDV','Maldives'
setAlpha3 'MEX','Mexico'
setAlpha3 'MHL','Marshall Islands'
setAlpha3 'MKD','Macedonia, the former Yugoslav Republic of'
setAlpha3 'MLI','Mali'
setAlpha3 'MLT','Malta'
setAlpha3 'MMR','Myanmar'
setAlpha3 'MNE','Montenegro'
setAlpha3 'MNG','Mongolia'
setAlpha3 'MNP','Northern Mariana Islands'
setAlpha3 'MOZ','Mozambique'
setAlpha3 'MRT','Mauritania'
setAlpha3 'MSR','Montserrat'
setAlpha3 'MTQ','Martinique'
setAlpha3 'MUS','Mauritius'
setAlpha3 'MWI','Malawi'
setAlpha3 'MYS','Malaysia'
setAlpha3 'MYT','Mayotte'
setAlpha3 'NAM','Namibia'
setAlpha3 'NCL','New Caledonia'
setAlpha3 'NER','Niger'
setAlpha3 'NFK','Norfolk Island'
setAlpha3 'NGA','Nigeria'
setAlpha3 'NIC','Nicaragua'
setAlpha3 'NIU','Niue'
setAlpha3 'NLD','Netherlands'
setAlpha3 'NOR','Norway'
setAlpha3 'NPL','Nepal'
setAlpha3 'NRU','Nauru'
setAlpha3 'NZL','New Zealand'
setAlpha3 'OMN','Oman'
setAlpha3 'PAK','Pakistan'
setAlpha3 'PAN','Panama'
setAlpha3 'PCN','Pitcairn'
setAlpha3 'PER','Peru'
setAlpha3 'PHL','Philippines'
setAlpha3 'PLW','Palau'
setAlpha3 'PNG','Papua New Guinea'
setAlpha3 'POL','Poland'
setAlpha3 'PRI','Puerto Rico'
setAlpha3 'PRK','Korea, Democratic People\'s Republic of'
setAlpha3 'PRT','Portugal'
setAlpha3 'PRY','Paraguay'
setAlpha3 'PSE','Palestine, State of'
setAlpha3 'PYF','French Polynesia'
setAlpha3 'QAT','Qatar'
setAlpha3 'REU','Réunion'
setAlpha3 'ROU','Romania'
setAlpha3 'RUS','Russian Federation'
setAlpha3 'RWA','Rwanda'
setAlpha3 'SAU','Saudi Arabia'
setAlpha3 'SDN','Sudan'
setAlpha3 'SEN','Senegal'
setAlpha3 'SGP','Singapore'
setAlpha3 'SGS','South Georgia and the South Sandwich Islands'
setAlpha3 'SHN','Saint Helena, Ascension and Tristan da Cunha'
setAlpha3 'SJM','Svalbard and Jan Mayen'
setAlpha3 'SLB','Solomon Islands'
setAlpha3 'SLE','Sierra Leone'
setAlpha3 'SLV','El Salvador'
setAlpha3 'SMR','San Marino'
setAlpha3 'SOM','Somalia'
setAlpha3 'SPM','Saint Pierre and Miquelon'
setAlpha3 'SRB','Serbia'
setAlpha3 'SSD','South Sudan'
setAlpha3 'STP','Sao Tome and Principe'
setAlpha3 'SUR','Suriname'
setAlpha3 'SVK','Slovakia'
setAlpha3 'SVN','Slovenia'
setAlpha3 'SWE','Sweden'
setAlpha3 'SWZ','Swaziland'
setAlpha3 'SXM','Sint Maarten (Dutch part)'
setAlpha3 'SYC','Seychelles'
setAlpha3 'SYR','Syrian Arab Republic'
setAlpha3 'TCA','Turks and Caicos Islands'
setAlpha3 'TCD','Chad'
setAlpha3 'TGO','Togo'
setAlpha3 'THA','Thailand'
setAlpha3 'TJK','Tajikistan'
setAlpha3 'TKL','Tokelau'
setAlpha3 'TKM','Turkmenistan'
setAlpha3 'TLS','Timor-Leste'
setAlpha3 'TON','Tonga'
setAlpha3 'TTO','Trinidad and Tobago'
setAlpha3 'TUN','Tunisia'
setAlpha3 'TUR','Turkey'
setAlpha3 'TUV','Tuvalu'
setAlpha3 'TWN','Taiwan, Province of China'
setAlpha3 'TZA','Tanzania, United Republic of'
setAlpha3 'UGA','Uganda'
setAlpha3 'UKR','Ukraine'
setAlpha3 'UMI','United States Minor Outlying Islands'
setAlpha3 'URY','Uruguay'
setAlpha3 'USA','United States of America'
setAlpha3 'UZB','Uzbekistan'
setAlpha3 'VAT','Holy See (Vatican City State)'
setAlpha3 'VCT','Saint Vincent and the Grenadines'
setAlpha3 'VEN','Venezuela, Bolivarian Republic of'
setAlpha3 'VGB','Virgin Islands, British'
setAlpha3 'VIR','Virgin Islands, U.S.'
setAlpha3 'VNM','Viet Nam'
setAlpha3 'VUT','Vanuatu'
setAlpha3 'WLF','Wallis and Futuna'
setAlpha3 'WSM','Samoa'
setAlpha3 'YEM','Yemen'
setAlpha3 'ZAF','South Africa'
setAlpha3 'ZMB','Zambia'
setAlpha3 'ZWE','Zimbabwe'
