Contact::UsState.create name: 'Alabama', code: 'AL'
Contact::UsState.create name: 'Alaska', code: 'AK'
Contact::UsState.create name: 'Arizona', code: 'AZ'
Contact::UsState.create name: 'Arkansas', code: 'AR'
Contact::UsState.create name: 'California', code: 'CA'
Contact::UsState.create name: 'Colorado', code: 'CO'
Contact::UsState.create name: 'Connecticut', code: 'CT'
Contact::UsState.create name: 'Delaware', code: 'DE'
Contact::UsState.create name: 'Florida', code: 'FL'
Contact::UsState.create name: 'Georgia', code: 'GA'
Contact::UsState.create name: 'Hawaii', code: 'HI'
Contact::UsState.create name: 'Idaho', code: 'ID'
Contact::UsState.create name: 'Illinois', code: 'IL'
Contact::UsState.create name: 'Indiana', code: 'IN'
Contact::UsState.create name: 'Iowa', code: 'IA'
Contact::UsState.create name: 'Kansas', code: 'KS'
Contact::UsState.create name: 'Kentucky', code: 'KY'
Contact::UsState.create name: 'Louisiana', code: 'LA'
Contact::UsState.create name: 'Maine', code: 'ME'
Contact::UsState.create name: 'Maryland', code: 'MD'
Contact::UsState.create name: 'Massachusetts', code: 'MA'
Contact::UsState.create name: 'Michigan', code: 'MI'
Contact::UsState.create name: 'Minnesota', code: 'MN'
Contact::UsState.create name: 'Mississippi', code: 'MS'
Contact::UsState.create name: 'Missouri', code: 'MO'
Contact::UsState.create name: 'Montana', code: 'MT'
Contact::UsState.create name: 'Nebraska', code: 'NE'
Contact::UsState.create name: 'Nevada', code: 'NV'
Contact::UsState.create name: 'New Hampshire', code: 'NH'
Contact::UsState.create name: 'New Jersey', code: 'NJ'
Contact::UsState.create name: 'New Mexico', code: 'NM'
Contact::UsState.create name: 'New York', code: 'NY'
Contact::UsState.create name: 'North Carolina', code: 'NC'
Contact::UsState.create name: 'North Dakota', code: 'ND'
Contact::UsState.create name: 'Ohio', code: 'OH'
Contact::UsState.create name: 'Oklahoma', code: 'OK'
Contact::UsState.create name: 'Oregon', code: 'OR'
Contact::UsState.create name: 'Pennsylvania', code: 'PA'
Contact::UsState.create name: 'Rhode Island', code: 'RI'
Contact::UsState.create name: 'South Carolina', code: 'SC'
Contact::UsState.create name: 'South Dakota', code: 'SD'
Contact::UsState.create name: 'Tennessee', code: 'TN'
Contact::UsState.create name: 'Texas', code: 'TX'
Contact::UsState.create name: 'Utah', code: 'UT'
Contact::UsState.create name: 'Vermont', code: 'VT'
Contact::UsState.create name: 'Virginia', code: 'VA'
Contact::UsState.create name: 'Washington', code: 'WA'
Contact::UsState.create name: 'West Virgina', code: 'WV'
Contact::UsState.create name: 'Wisconsin', code: 'WI'
Contact::UsState.create name: 'Wyoming', code: 'WY'
Contact::UsState.create name: 'Distict of Columbia', code: 'DC'