Contact::CanadaProvince.create name: 'Alberta', code: 'AB'
Contact::CanadaProvince.create name: 'British Columbia', code: 'BC'
Contact::CanadaProvince.create name: 'Manitoba', code: 'MB'
Contact::CanadaProvince.create name: 'New Brunswick', code: 'NB'
Contact::CanadaProvince.create name: 'Newfoundland and Labrador', code: 'NL'
Contact::CanadaProvince.create name: 'Nova Scotia', code: 'NS'
Contact::CanadaProvince.create name: 'Ontario', code: 'ON'
Contact::CanadaProvince.create name: 'Prince Edward Island', code: 'PE'
Contact::CanadaProvince.create name: 'Quebec', code: 'QC'
Contact::CanadaProvince.create name: 'Saskatchewan', code: 'SK'
Contact::CanadaProvince.create name: 'Northwest Territories', code: 'NT'
Contact::CanadaProvince.create name: 'Yukon', code: 'YT'
Contact::CanadaProvince.create name: 'Nunavut', code: 'NU'